### ISSUE TITLE
Ktor HttpClient (native/curl): json deserialization doesn't work when using a proxy 

### ISSUE THREAD

**Issue by BoD** [ktorio/ktor#1548]
**Ktor Version and Engine Used (client or server and name)**
```
plugins {
    id 'org.jetbrains.kotlin.multiplatform' version '1.3.61'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.3.61'
}

...

        commonMain {
            dependencies {
                implementation kotlin('stdlib-common')
                implementation "org.jetbrains.kotlinx:kotlinx-io:0.1.16"
                implementation "io.ktor:ktor-client-core:1.3.0-rc2"
                implementation "io.ktor:ktor-client-json:1.3.0-rc2"
                implementation "io.ktor:ktor-client-serialization:1.3.0-rc2"
                implementation("io.ktor:ktor-client-logging:1.3.0-rc2")
            }
        }

...

        macosMain {
            dependencies {
                implementation "org.jetbrains.kotlinx:kotlinx-io-native:0.1.16"
                implementation "io.ktor:ktor-client-serialization-native:1.3.0-rc2"
                implementation "io.ktor:ktor-client-json-native:1.3.0-rc2"
                implementation "io.ktor:ktor-client-curl:1.3.0-rc2"
                implementation("io.ktor:ktor-client-logging-native:1.3.0-rc2")
            }
        }
```
**Describe the bug**
When using a proxy (
```
engine {
    proxy = ProxyBuilder.http(URLBuilder().apply {
        host = "localhost"
        port = 8888
    }.build())
}
```
), on the JVM, everything works fine.

But on native, serialization breaks, I get 
```
Uncaught Kotlin exception: io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.utils.io.ByteChannelNative -> class org.jraf.klibqonto.internal.api.model.organizations.ApiOrganizationEnvelope 
```

**To Reproduce**
Use Ktor HttpClient with json serialization on native (in my case, MacOS) and configure a proxy, and run it.  The above exception is thrown.

**Expected behavior**
Serialization should work with a proxy.

**Comment by cy6erGn0m** [comment]
Fixed in 1.3.0

**Comment by BoD** [comment]
Hi!  Unfortunately I can still reproduce the issue after updating to 1.3.0.  Please let me know if you need repro steps, I do have a project that easily shows the problem, but it needs credentials to access a specific API - I would have to get them to you privately somehow.

**Comment by BoD** [comment]
Hi! Can this be re-opened please?  I can still reproduce it in 1.4.0.

**Comment by Stexxe** [comment]
@BoD thank you, I've reproduced it. Please follow the new issue [KTOR-955](https://youtrack.jetbrains.com/issue/KTOR-955) I've created in Youtrack.

**Comment by e5l** [comment]
Fixed in 1.4.2
