### ISSUE TITLE
Ktor Client JS: request to /example requests http://localhost/example

### ISSUE THREAD

**Issue by Ribesg** [ktorio/ktor#1695]
**Ktor Version and Engine Used (client or server and name)**
Ktor Client Common 1.3.1, in browser (JS)

**Describe the bug**
request to /example requests http://localhost/example

**To Reproduce**
1. Clone https://github.com/Ribesg/Kita/tree/2c7941183ebcde1fc2193bd00a1bed53f1249b10 on a machine which can be reached from the network (a server)
    ````
    git clone https://github.com/Ribesg/Kita
    cd Kita
    git reset --hard 2c7941183ebcde1fc2193bd00a1bed53f1249b10
    ````
2. Run `./runServer.sh`
3. Browse to `https://yourserver:12345`
4. Try to login using whatever credentials (correct ones are admin/admin)
5. See failing requests to `https://localhost/api/auth/login` instead of `https://yourserver:12345/api/auth/login` in the console

**Expected behavior**
Requests should use the current `location.origin` when none is provided in the browser

**Comment by e5l** [comment]
Hi @Ribesg, thanks for the report. I'll be fixed in the next minor release

**Comment by SebastianAigner** [comment]
For anyone else looking, this bug is still present in 1.3.2. :)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-453">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
I can still reproduce it using Ktor 1.6.0 when running a development server with the following code:
```kt
GlobalScope.launch {
     val client = HttpClient(Js)
     val r = client.get<String>("/example")
}
```

**Comment by Benjoyo** [comment]
Any updates? Still present in 1.6.7.
