### ISSUE TITLE
Ktor with Android client throws IllegalStateException - responseMessage must not be null

### ISSUE THREAD

**Issue by Hakky54** [ktorio/ktor#1812]
**Ktor Version and Engine Used (client or server and name)**
Version 1.3.1 of Ktor client with Android module

**Describe the bug**
When I do a get request I am getting `Exception in thread "main" java.lang.IllegalStateException: connection.responseMessage must not be null`

**To Reproduce**
* Running with Java 11, with maven, kotlin stdlib and org.jetbrains.kotlin maven plugin.
```
import io.ktor.client.HttpClient
import io.ktor.client.engine.android.Android
import io.ktor.client.request.get
import io.ktor.client.statement.HttpResponse
import io.ktor.utils.io.readUTF8Line
import kotlinx.coroutines.runBlocking

fun main() {

    runBlocking {
        val response: HttpResponse = HttpClient(Android).get("http://api.chucknorris.io/jokes/random")

        print(response.status.value)
        print(response.content.readUTF8Line())
    }

}
```

**Expected behavior**
I would expect it should print the status code and response message, but it doesn't reach at that point.

**Screenshots**
<img width="813" alt="Screenshot 2020-04-21 at 12 53 59" src="https://user-images.githubusercontent.com/16032204/79858163-435f2800-83cf-11ea-8ede-f670a999ad43.png">

**Comment by Hakky54** [comment]
I discovered that the some servers don't always send the reasonPrase. I am using Tomcat and they mentioned it is disabled by default, but can be enabled. However this option is deprecated and the switch will be removed for the next release. I am not quite sure if other servers always do send the reasonPhrase.

AndroidClientEngine requires the reasonPhrase at line number 85 `val statusCode = HttpStatusCode(connection.responseCode, connection.responseMessage)` Would it be possible to make the reasonPhrease optional within the AndroidClientEngine?

**Comment by Hakky54** [comment]
This issue is fixed with the following pull request: https://github.com/ktorio/ktor/pull/1852

**Comment by rolfwessels** [comment]
I'm on Version **1.3.2** of Ktor client and I am still having this issues. The API calls work when I am running in app but under MPP unit testing I get the same exception. 

```groovy
sourceSets["androidTest"].dependencies {
        implementation("io.ktor:ktor-client-android:1.3.2")
       ...
}
```

```kotlin
    @Test
    @Tag("IntegrationTest")
    fun `Failing`() = runBlocking  {

        val response: HttpResponse = HttpClient().get("http://api.chucknorris.io/jokes/random")

        print(response.status.value)
        print(response.content.readUTF8Line())

    }
```

**Exception**
```
Caused by: java.lang.IllegalStateException: connection.responseMessage must not be null
	at io.ktor.client.engine.android.AndroidClientEngine.execute(AndroidClientEngine.kt:85)
	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

```

**Comment by Hakky54** [comment]
Hi @rolfwessels 

This bug has been fixed but not available yet. The latest release is from March 2020 while the bug has been fixed at April 2020. They still need to release a new version of the library including the bug fix. 

Hi @e5l, any idea when the next release will be made?

**Comment by rolfwessels** [comment]
Is there any work around for this?

**Comment by e5l** [comment]
Just made one. Sorry for the delay, please check `1.4.0`

**Comment by rolfwessels** [comment]
@e5l Thanks, appreciate it.
