### ISSUE TITLE
Ktor 1.3.2 missing from Maven Central

### ISSUE THREAD

**Issue by alvarosanchez** [ktorio/ktor#1942]
It is in JCenter, but not in Central.

I noticed you guys use Bintray to synchronize with Maven Central. Been there, done that. My advise: don't. Instead, use both [Nexus Staging plugin](https://github.com/Codearte/gradle-nexus-staging-plugin) and [Nexus Publish Plugin](https://github.com/marcphilipp/nexus-publish-plugin).

Note that both plugins are being merged into [a new Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin), but that's a work in progress. In Micronaut, we still use the former 2, and other than Maven Central being down, it is a much faster and reliable process.

**Comment by graemerocher** [comment]
Would you guys be able to get this version into Maven Central soon? We need this version is central for Micronaut.

**Comment by jamesward** [comment]
This tripped me up too.  Please get this in Central.

**Comment by averikitsch** [comment]
+1

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-342">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed starting from `1.4.0`

**Comment by drvdijk** [comment]
Can you retroactively get the 1.3.2 version in maven central? That would make Micronaut users that can't use jcenter quite happy

**Comment by alvarosanchez** [comment]
@e5l the issue reported is that 1.3.2 is not in Central, and as far as I can tell, it still isn't.

Can you please publish that version to Maven Central?

**Comment by e5l** [comment]
Nope, `1.3.2` has the wrong sign so the Bintray refuses to sync it with maven central. We can't override files and do that again, I'm sorry.
