### ISSUE TITLE
Exception in routing does not output stacktrace with CallLogging installed.

### ISSUE THREAD

**Issue by spand** [ktorio/ktor#354]
The testcase below should print the exception that occurs during routing. Related to #353 
```
    @Location("/items/{itemId}/{extra?}")
    class OverlappingPath1(val itemId: Int, val extra: String?)

    @Location("/items/{extra}")
    class OverlappingPath2(val extra: String)

    @Test
    fun `overlapping paths are resolved as expected`() = withLocationsApplication {
        application.install(CallLogging)
        application.routing {
            get<OverlappingPath1> {
                call.respond(HttpStatusCode.OK)
            }
            get<OverlappingPath2> {
                call.respond(HttpStatusCode.OK)
            }
        }
        urlShouldBeHandled(application.locations.href(OverlappingPath1(1, "Foo")))
        urlShouldBeHandled(application.locations.href(OverlappingPath2("1-Foo")))
    }
```

**Comment by e5l** [comment]
Fixed here https://github.com/ktorio/ktor/commit/bad2b3a6cd426725673077bea38aefc3cbcd7d06

**Comment by lamba92** [comment]
I think I'm encountering this problem but I'm not sure. Whenever I call one of the routes genereted with the code below a strange error appears:
```
WARN ktor.application - it.lamba.utils.AbstractCoroutineWorker.start$default(Lit/lamba/utils/AbstractCoroutineWorker;ZILjava/lang/Object;)V
```
Even with `CallLogging` the printed out error remains this one. I have no Idea why.
[`AbstractCoroutineWorker`](https://github.com/lamba92/KCoroutineWorker/blob/master/src/main/kotlin/it/lamba/utils/AbstractCoroutineWorker.kt)

```kotlin
object MyWorker: AbstractCoroutineWorker {...}
...
route("workers") {
    buildRoutesFor(MyWorker)
}
```
```kotlin
fun Route.buildRoutesFor(worker: AbstractCoroutineWorker) {
    route(worker.javaClass.simpleName) {
        get("status") {
            call.respond(worker.status)
        }
        get("start") {
            worker.start()
            call.respond(HttpStatusCode.OK)
        }
        get("stop") {
            worker.stop(true)
            call.respond(HttpStatusCode.OK)
        }
        get("reset") {
            worker.reset(true)
            call.respond(HttpStatusCode.OK)
        }
    }
}
```

**Comment by e5l** [comment]
Hi @lamba92, could you create the separate issue?
