### ISSUE TITLE
No configuration setting found for key 'ktor'

### ISSUE THREAD

**Issue by kodal** [ktorio/ktor#484]
Run exception
```
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ktor'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:37)
	at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt:57)
	at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt)
	at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.build(ApplicationEngineEnvironment.kt:55)
	at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:38)
	at io.ktor.server.engine.CommandLineKt.commandLineEnvironment(CommandLine.kt:50)
	at io.ktor.server.netty.DevelopmentEngine.main(DevelopmentEngine.kt:13)
```

### `build.gradle.kts`

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.gradle.dsl.Coroutines

val ktor_version = "0.9.3"

plugins {
    application
    kotlin("jvm") version "1.2.51"
}

application {
    mainClassName = "io.ktor.server.netty.DevelopmentEngine"
}

group = "ktor3"
version = "1.0-SNAPSHOT"

repositories {
    jcenter()
    maven("http://kotlin.bintray.com/ktor")
    mavenCentral()
}


dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("ch.qos.logback:logback-classic:1.2.1")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
kotlin {
    experimental.coroutines = Coroutines.ENABLE
}
```

### `application.conf`

```groovy
ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [ com.kodal.AppKt.main ]
  }
  security {

  }
}
```

### `App.kt`

```kotlin
package com.kodal

import io.ktor.application.Application
import io.ktor.application.call
import io.ktor.application.install
import io.ktor.features.CallLogging
import io.ktor.features.DefaultHeaders
import io.ktor.response.respondText
import io.ktor.routing.Routing
import io.ktor.routing.get

fun Application.main() {
    install(DefaultHeaders)
    install(CallLogging)
    install(Routing) {
        get("/") {
            call.respondText("Hello")
        }
    }
}
```

**Comment by kodal** [comment]
<img width="444" alt="screen shot 2018-07-18 at 18 42 19" src="https://user-images.githubusercontent.com/16075154/42882728-4f83322a-8abb-11e8-9679-77a5cb6efa3a.png">
I think it's in right place and defining sourceSet

**Comment by soywiz** [comment]
Try to generate a sample project with this and try if it happens to you there: http://ktor.io/quickstart/generator.html

**Comment by kodal** [comment]
I tried with intellij idea plugin, same exception

**Comment by soywiz** [comment]
Let's check a few things:

- In the images you are using the gradle kotlin-dsl, have you tried without it? (generator do not use it, so I guess if you tried with it, it is not related to it, but let's confirm it)
- Which IntelliJ version are you using?
- Which Java version have you installed and configured?
- Which Kotlin version have you in the IDE? `Tools -> Kotlin -> Configure Plugin updates`
- Have you tried to run it from the terminal `./gradlew run`? Maybe your IntelliJ/Kotlin in the IDE has something wrong

**Comment by kodal** [comment]
I tried with terminal and it worked. Intellij IDEA 2018.2 RC

**Comment by soywiz** [comment]
Can you join slack https://slack.kotlinlang.org/ `#ktor` channel and continue the troubleshooting there?

**Comment by kodal** [comment]
Ok

**Comment by ti4n1993** [comment]
I met this too when I create ktor project with kotlin gradle dsl.
**build.gradle.kts**
`kotlin.sourceSets["main"].kotlin.srcDirs("src")
kotlin.sourceSets["test"].kotlin.srcDirs("test")`
I think it should contains sources dir like this
`kotlin.sourceSets["main"].kotlin.srcDirs("src")`
but it doesn't work @soywiz

**Comment by ti4n1993** [comment]
Yes,it only contains
`kotlin.sourceSets["main"].kotlin.srcDirs("src")`
`kotlin.sourceSets["test"].kotlin.srcDirs("test")`

**Comment by soywiz** [comment]
Should be fixed in the next version: https://github.com/ktorio/ktor-init-tools/commit/31d183f9da0f7ee3ef7877dabf3d643ae2c32779

**Comment by ti4n1993** [comment]
Thanks, but I want to know why it didn't work after I added
```
kotlin.sourceSets["main"].resources.srcDirs("resources"))
```
manually

**Comment by randallmitchell** [comment]
I've also manually added the `resources` directory to my `sourceSets` and still have the given error.  Is the change actually going to fix the issue?

**Comment by laeur** [comment]
@ti4n1993 , @randallmitchell , you should add resources folder without kotlin prefix
`kotlin.sourceSets["main"].kotlin.srcDirs("src")
sourceSets["main"].resources.srcDir("resources")
kotlin.sourceSets["test"].kotlin.srcDirs("test")`

**Comment by ti4n1993** [comment]
Thanks
